language: go

go:
    - 1.6
    - 1.7

script: go test -bench=.

notifications:
    email:
        recipients:
            - benjamin@bengfort.com
        on_success: change
        on_failure: always
